# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a0c1afacbf968c18201a77248d2302502cc52de3e125b95a2d9ad200645ffee3bc93aa824f6b4baf67058d3a4754c8f71b81f731c150133d893ef638d50dc9f

test:
  secret_key_base: 804ba51a147ccb52ffd7dbbdef807eb437a7f587c2c5d125b052465bddce85d9523b8d1febb0eeaac7fbfbc11a43777ad95342ed5717723a34043f87207e7fa2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
